### ISSUE TITLE
ManagedDevices_Hardware_Get.ps1 doesnt return ICCID

### ISSUE THREAD

**Issue by jimmyeao** [microsoftgraph/powershell-intune-samples#97] opened 2019-06-20 14:58 UTC
the script ManagedDevices_Hardware_Get.ps1 returns an empty value for ICCID, despite one being shown in the Intune Portal for a device. We really need a way of reporting on ICCID numbers.

**Comment by kevsully** [comment] 2019-06-20 17:46
Hi Jimmyeao, I'll try to take a look but ICCID (and UDID) only come down for individual devices and only when explicitly requested. So you would have to pull the individual device then loop through if you have multiple. Something like this... https://graph.microsoft.com/beta/deviceManagement/manageddevices('deviceID')?$select=id,hardwareinformation,activationLockBypassCode,iccid,udid

**Comment by davefalkus** [comment] 2019-06-20 17:47
Thanks @kevsully.

Found the issue with the script not returned the ICCID value, looking at doing an update for it now.

Dave

**Comment by davefalkus** [comment] 2019-06-20 18:07
@jimmyeao, we've just updated the sample script with ICCID and UDID output to CSV, I've just tested it and it works, could you confirm?

https://github.com/microsoftgraph/powershell-intune-samples/blob/master/ManagedDevices/ManagedDevices_Hardware_Get.ps1

**Comment by davefalkus** [comment] 2019-06-24 19:09
@jimmyeao, 

Does it work for you now, so we can close the issue?

Dave

**Comment by jimmyeao** [comment] 2019-06-24 20:42
Apologies, have been off work, will test I’m the morning

Jimmy White
________________________________

**Comment by jimmyeao** [comment] 2019-06-25 08:09
It appears to be bringing back duplicates now, have checked against the records in Intune, and these are the wrong ICCID numbers for the devices
354070097620145	samsung	SM-G390F		GSM	A4:6C:F1:03:ED:DC	en-GB	FALSE	TRUE	FALSE				meetHardwareRequirements	running	running	89441000300364300000
359108095006332	samsung	SM-G390F		GSM	10:8E:E0:9B:41:88	en-GB	FALSE	TRUE	FALSE				meetHardwareRequirements	running	running	89441000300364300000
354070097548411	samsung	SM-G390F		GSM	68:5A:CF:F6:80:71	en-GB	FALSE	TRUE	FALSE				meetHardwareRequirements	running	running	89441000300364300000
354070097547967	samsung	SM-G390F		GSM		en-GB	FALSE	TRUE	FALSE				meetHardwareRequirements	running	running	89441000300364300000
354070097548890	samsung	SM-G390F		GSM	68:5A:CF:F6:80:D1	en-GB	FALSE	TRUE	FALSE				meetHardwareRequirements	running	running	89441000300364300000
354070097534247	samsung	SM-G390F		GSM	68:5A:CF:F6:75:5F	en-GB	FALSE	TRUE	FALSE				meetHardwareRequirements	running	running	89441000300364300000
354070097534247	samsung	SM-G390F		GSM	68:5A:CF:F6:75:5F	en-GB	FALSE	TRUE	FALSE				meetHardwareRequirements	running	running	89441000300364300000
354070097565878	samsung	SM-G390F		GSM	68:5A:CF:F6:8E:15	en-GB	FALSE	TRUE	FALSE				meetHardwareRequirements	running	running	89441000300364300000

**Comment by jimmyeao** [comment] 2019-06-25 08:32
Actually, not duplicates, on ICCID numbers that don't have spaces, its missing the last 6 digits off and replacing them with zeros

**Comment by davefalkus** [comment] 2019-06-25 18:03
I can't reproduce the behaviour my side, are all sim cards affected with the 5 zeros?

**Comment by jimmyeao** [comment] 2019-06-25 18:36
No, some that have a space every 5th char are ok. I seem to remember seeing this in power query when using airwatch, had to format the output as text or we saw the same behaviour

Jimmy White
________________________________

**Comment by jimmyeao** [comment] 2019-08-12 14:03
Ok, so it would seem this is potentially an Office issue.
the value stored in the CSV when opening in Excel appears to truncate the number

so 89441000300364350748 appears as 89441000300364300000 
changing the format of the cell does not help with imported data. Another oddity, if I copy 89441000300364350748 and paste it into a cell formatted as a number, Excel changes it to 89441000300364300000. A quick google turns up the fact that Excel can only handle up to 15 digits in a number, and it would seem that we need to precede the number in the CSV with a ' so it is displayed correctly. This may affect other fields in the report also

**Comment by jimmyeao** [comment] 2019-08-12 14:20
Just to add, for anyone else facing the same issue, instead of opening the CSV directly in Excel, open a blank excel workbook and use the Get Data - From Text/CSV function to import the data. The ICCID is then correctly displayed.

**Comment by davefalkus** [comment] 2019-08-13 18:18
Thanks for confirming the behaviour @jimmyeao.

I will close the issue, please reopen if its still an issue.

**Closed by davefalkus** 2019-08-13 18:18 UTC

**Comment by AllIsStillTaken** [comment] 2021-04-29 11:41
This script does not include Co-management windows 10 devices.
Does anyone know, how I can change this?
